# Generated by Django 3.2.16 on 2024-09-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_seriesrandomnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('randomnumber_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.randomnumber')),
            ],
            bases=('testing.randomnumber',),
        ),
        migrations.CreateModel(
            name='VoisinsDeZero',
            fields=[
                ('randomnumber_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.randomnumber')),
            ],
            bases=('testing.randomnumber',),
        ),
        migrations.CreateModel(
            name='ZeroSpiel',
            fields=[
                ('randomnumber_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.randomnumber')),
            ],
            bases=('testing.randomnumber',),
        ),
        migrations.RenameModel(
            old_name='SeriesRandomNumber',
            new_name='Orphelins',
        ),
    ]
